apiVersion: v1
kind: Service
metadata:
  name: {{ include "osdu.fullname" . }}
  labels:
    {{- include "osdu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "osdu.selectorLabels" . | nindent 4 }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: osdu-helm-charts
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: osdu-helm-charts
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.1
    helm.sh/chart: grafana-7.3.11
  name: grafana-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - grafana.baremetal-dev0b.epm-osdu.projects.epam.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: common-tfcert
      mode: SIMPLE