name: Release Helm Chart

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Package Helm chart
        run: helm package .

      - name: Create index.yaml
        run: helm repo index . --url https://oaperezb.github.com/osdu-helm-charts

      - name: Commit and push
        run: |
          git config --local user.email "omar_perez@epam.com"
          git config --local user.name "omar_perez"
          git add .
          git commit -m "Release new chart version"
          git push